### ISSUE TITLE
Build issues on Open Pandora (GNU/Linux ARM)

### ISSUE THREAD

**Issue by sviscapi** [letoram/arcan#110]
Hi,

Out of curiosity, I tried to build Arcan on my Open Pandora this morning:

https://pyra-handheld.com/boards/pages/pandora/

I had several issues, but I managed to solve almost all of them:

- had to replace CLOCK_MONOTONIC_RAW with CLOCK_MONOTONIC in src/platform/posix/time.c
- had to add -liconv to the linker flags
- still stuck on this one though: is TIOCSIG (asm/ioctls.h) compatible with the ARM architecture ?

[ 75%] Building C object 
frameserver/terminal/CMakeFiles/afsrv_terminal.dir/default/tsm/shl-pty.c.o
/media/Pandora1/dev/arcan/arcan/src/frameserver/terminal/default/tsm/shl-pty.c: 
In function ???shl_pty_signal???:
/media/Pandora1/dev/arcan/arcan/src/frameserver/terminal/default/tsm/shl-pty.c:4
51:24: 
error: ???TIOCSIG??? undeclared (first use in this function)
  return ioctl(pty->fd, TIOCSIG, sig) < 0 ? -errno : 0;
                        ^~~~~~~
/media/Pandora1/dev/arcan/arcan/src/frameserver/terminal/default/tsm/shl-pty.c:4
51:24: 
note: each undeclared identifier is reported only once for each 
function it appears in
/media/Pandora1/dev/arcan/arcan/src/frameserver/terminal/default/tsm/shl-pty.c:4
52:1: 
warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
frameserver/terminal/CMakeFiles/afsrv_terminal.dir/build.make:86: 
recipe for target 
'frameserver/terminal/CMakeFiles/afsrv_terminal.dir/default/tsm/shl-pty.c.o' 
failed
make[2]: *** 
[frameserver/terminal/CMakeFiles/afsrv_terminal.dir/default/tsm/shl-pty.c.o] 
Error 1
CMakeFiles/Makefile2:504: recipe for target 
'frameserver/terminal/CMakeFiles/afsrv_terminal.dir/all' failed
make[1]: *** [frameserver/terminal/CMakeFiles/afsrv_terminal.dir/all] 
Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

Could you please have a look at it ?

Cheers, Sam a.k.a "Magic Sam" from the Open Pandora community

**Comment by letoram** [comment]
There's probably going to be more bring-up issues than these as I don't have anything with PowerVR to try. but let's give it a go. Is there any QEmu- workable devimage to start with?

Probing for CLOCK_MONOTONIC v. CLOCK_MONOTONIC_RAW should be added to the build system anyhow so I'll look into that. Advanced engine features will probably sting for a bit, so lets start easier. Add -DNO_FSRV=ON to your cmake and it should ignore the frameservers entirely for the time being. How far do you get then?

I've built on ARM in other environments (non-public android port and raspberry- pi) so there's something else going on with the TIOCSIG..

**Comment by sviscapi** [comment]
Hi :)

Some good news first: 

- Compilation completes successfully when frameservers are turned off.
- It also completes successfully when they are turned on though, provided the following lines are added to /src/frameserver/terminal/default/tsm/shl-pty.c :

#ifndef TIOCSIG
#define FIOQSIZE 0x545E
#include <asm/ioctls.h>
#define TIOCSIG  _IOW('T', 0x36, int)  /* pty: generate signal */
#endif

The Open Pandora runs Linux 3.2.84, and TIOCSIG doesn't seem to be present in our include files. So I just copied the relevant bit from a more recent kernel version:

https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable.git/tree/arch/arm/include/asm/ioctls.h?id=refs/tags/v3.2.88

https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable.git/tree/include/asm-generic/ioctls.h?id=refs/tags/v3.2.88

Cheers, Sam

**Comment by sviscapi** [comment]
And now the bad news :

./arcan -p ../data/resources/ ../data/appl/welcome, when Aran is built with "-DVIDEO_PLATFORM=sdl" and "-DAGP_PLATFORM=gl21", crashes with the following error message:

agp lookup(glEnableVertexAttribArray) failed, missing req. symbol.
Aborted

N.B: the Open Pandora is not compatible with stock OpenGL, only with OpenGL ES... In order to run OpenGL applications, we use a wrapper library, gl4es:

https://github.com/ptitseb/gl4es

Looks like glEnableVertexAttribArray is not yet implemented in this library. I'll ask the author if he could do something about it.

Next, I tried to compile Arcan with  "-DAGP_PLATFORM=gles2". But this time, it failed with the following error message:

[ 41%] Building C object CMakeFiles/arcan.dir/platform/agp/glshared.c.o
/media/Pandora1/dev/arcan/arcan/src/platform/agp/glshared.c: In function ���agp_rendertarget_swap���:
/media/Pandora1/dev/arcan/arcan/src/platform/agp/glshared.c:60:21: error: ���GL_DRAW_FRAMEBUFFER_BINDING��� undeclared (first use in this function)
  env->get_integer_v(GL_DRAW_FRAMEBUFFER_BINDING, &cfbo);
                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/media/Pandora1/dev/arcan/arcan/src/platform/agp/glshared.c:60:21: note: each undeclared identifier is reported only once for each function it appears in
/media/Pandora1/dev/arcan/arcan/src/platform/agp/glshared.c: In function ���agp_pipeline_hint���:
/media/Pandora1/dev/arcan/arcan/src/platform/agp/glshared.c:384:40: error: ���GL_FILL��� undeclared (first use in this function)
   env->polygon_mode(GL_FRONT_AND_BACK, GL_FILL);
                                        ^~~~~~~
/media/Pandora1/dev/arcan/arcan/src/platform/agp/glshared.c: In function ���agp_update_vstore���:
/media/Pandora1/dev/arcan/arcan/src/platform/agp/glshared.c:538:21: error: ���GL_UNPACK_ROW_LENGTH��� undeclared (first use in this function)
   env->pixel_storei(GL_UNPACK_ROW_LENGTH, 0);
                     ^~~~~~~~~~~~~~~~~~~~
/media/Pandora1/dev/arcan/arcan/src/platform/agp/glshared.c: In function ���agp_submit_mesh���:
/media/Pandora1/dev/arcan/arcan/src/platform/agp/glshared.c:776:42: error: ���GL_LINE��� undeclared (first use in this function)
     env->polygon_mode(GL_FRONT_AND_BACK, GL_LINE);
                                          ^~~~~~~
/media/Pandora1/dev/arcan/arcan/src/platform/agp/glshared.c:782:42: error: ���GL_FILL��� undeclared (first use in this function)
     env->polygon_mode(GL_FRONT_AND_BACK, GL_FILL);
                                          ^~~~~~~
CMakeFiles/arcan.dir/build.make:878: recipe for target 'CMakeFiles/arcan.dir/platform/agp/glshared.c.o' failed
make[2]: *** [CMakeFiles/arcan.dir/platform/agp/glshared.c.o] Error 1
CMakeFiles/Makefile2:68: recipe for target 'CMakeFiles/arcan.dir/all' failed
make[1]: *** [CMakeFiles/arcan.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

What am I doing wrong ?

Cheers, Sam

**Comment by letoram** [comment]
You might have some luck jumping back a version or two, a lot of work in the master branch on getting multi-vendor-multi-GPU + driver hotswapping working. How's the 0.5.1 or 0.5.0 tag reacting?

**Comment by letoram** [comment]
I pushed an update to master that should make the AGP backend build on some (not OSX at least) GL libraries at least, how much - if anything - that will actually work is in the hands of the driver gods.

**Comment by sviscapi** [comment]
Hi,

Thanks for working on the GLES build issues, it's really appreciated.

Compilation still fails, but for another reason:

[ 57%] Building C object shmif/CMakeFiles/arcan_shmif_intext.dir/x11/x11.c.o
In file included from /mnt/utmp/codeblocks/usr/include/GL/glx.h:45:0,
                 from /media/Pandora1/dev/arcan/arcan/src/shmif/x11/x11.c:12:
/mnt/utmp/codeblocks/usr/include/GL/gl.h:1322:23: error: conflicting types for ���glTexImage2D���
 GLAPI void GLAPIENTRY glTexImage2D( GLenum target, GLint level,
                       ^~~~~~~~~~~~
In file included from /media/Pandora1/dev/arcan/arcan/src/platform/agp/glfun.h:15:0,
                 from /media/Pandora1/dev/arcan/arcan/src/shmif/x11/x11.c:10:
/mnt/utmp/codeblocks/usr/include/GLES2/gl2.h:576:37: note: previous declaration of ���glTexImage2D��� was here
 GL_APICALL void         GL_APIENTRY glTexImage2D (GLenum target, GLint level, GLenum internalformat, GLsizei width, GLsizei height, GLint border, GLenum format, GLenum type, const GLvoid* pixels);
                                     ^~~~~~~~~~~~
In file included from /mnt/utmp/codeblocks/usr/include/GL/gl.h:2085:0,
                 from /mnt/utmp/codeblocks/usr/include/GL/glx.h:45,
                 from /media/Pandora1/dev/arcan/arcan/src/shmif/x11/x11.c:12:
/mnt/utmp/codeblocks/usr/include/GL/glext.h:6152:19: error: conflicting types for ���GLintptr���
 typedef ptrdiff_t GLintptr;
                   ^~~~~~~~
In file included from /media/Pandora1/dev/arcan/arcan/src/platform/agp/glfun.h:15:0,
                 from /media/Pandora1/dev/arcan/arcan/src/shmif/x11/x11.c:10:
/mnt/utmp/codeblocks/usr/include/GLES2/gl2.h:35:26: note: previous declaration of ���GLintptr��� was here
 typedef khronos_intptr_t GLintptr;
                          ^~~~~~~~
In file included from /mnt/utmp/codeblocks/usr/include/GL/gl.h:2085:0,
                 from /mnt/utmp/codeblocks/usr/include/GL/glx.h:45,
                 from /media/Pandora1/dev/arcan/arcan/src/shmif/x11/x11.c:12:
/mnt/utmp/codeblocks/usr/include/GL/glext.h:6153:19: error: conflicting types for ���GLsizeiptr���
 typedef ptrdiff_t GLsizeiptr;
                   ^~~~~~~~~~
In file included from /media/Pandora1/dev/arcan/arcan/src/platform/agp/glfun.h:15:0,
                 from /media/Pandora1/dev/arcan/arcan/src/shmif/x11/x11.c:10:
/mnt/utmp/codeblocks/usr/include/GLES2/gl2.h:36:26: note: previous declaration of ���GLsizeiptr��� was here
 typedef khronos_ssize_t  GLsizeiptr;
                          ^~~~~~~~~~
shmif/CMakeFiles/arcan_shmif_intext.dir/build.make:62: recipe for target 'shmif/CMakeFiles/arcan_shmif_intext.dir/x11/x11.c.o' failed
make[2]: *** [shmif/CMakeFiles/arcan_shmif_intext.dir/x11/x11.c.o] Error 1
CMakeFiles/Makefile2:223: recipe for target 'shmif/CMakeFiles/arcan_shmif_intext.dir/all' failed
make[1]: *** [shmif/CMakeFiles/arcan_shmif_intext.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

Could you do something about it please ?

Cheers, Sam

**Comment by letoram** [comment]
Ok, so GLX pulls in GL headers and they start creating colliding symbols because GL != GLES.
Update to master and rerun cmake with -DENABLE_LWA=OFF

**Comment by sviscapi** [comment]
Hi,

I'm sorry but your latest changes didn't solve the issue :( I get the exact same error as before (with -DENABLE_LWA=OFF, and even after a fresh "git clone").

Cheers, Sam

**Comment by letoram** [comment]
that's.. odd, the configure- step from cmake, what does the "--- Conguration results:" step say? The [Headless] section should be [stub].

**Comment by sviscapi** [comment]
Hmm, Headless = x11 on my end...

/media/Pandora1/dev/arcan/arcan/build$ cmake -DCMAKE_BUILD_TYPE="Debug" -DVIDEO_PLATFORM=sdl -DAGP_PLATFORM=gles2 -DENABLE_LWA=OFF ../src

---- Configuration results:
Compiler	GNU
Video   	sdl
AGP     	gles2
Audio   	openal
Input   	sdl
Headless	x11
Lua     	luajit51

What am I doing wrong ?

Cheers, Sam

**Comment by letoram** [comment]
did a clean checkout in a VM with your lines here, oddly enough, I get stub. The last patch to the build scripts is very rigid as well (enable_lwa set to off? then force headless to stub).
For the sake of testing, you can just hack around it by patching:
src/platform/cmake/CMakeLists.VIDEO:85 and force it to stub there :)

**Comment by sviscapi** [comment]
OK, compilation completed successfully, but the welcome application fails to run:

export SDL_VIDEO_GLES2=1
export SDL_VIDEO_GL_DRIVER=libGLESv2.so

/media/Pandora1/dev/arcan/arcan/build$ ./arcan -p ../data/resources/ ../data/appl/welcome
Notice: [SDL] Video Info: 800, 480, hardware acceleration: no, window manager: yes, MSAA: 4
platform_video_init() failed.
Error: couldn't initialize video subsystem. Check permissions,  try other video platform options (-f, -w, -h)
Video platform environment variables:
	ARCAN_VIDEO_MULTISAMPLES=1 - attempt to enable multisampling

Video platform initialization failed
Aborted

Cheers, Sam

**Comment by letoram** [comment]
so it's the platform/sdl/video.c:39x SDL_SetVideoMode(800, 480, 32, SDL_OPENGL) call that fails,
if https://pandorawiki.org/GLES is accurate, that one needs changing on pandora.

**Comment by sviscapi** [comment]
OK, If I understand correctly, SDL on the Pandora should be initialized with SDL_SetVideoMode(800, 480, 16, SDL_OPENGLES), not with SDL_SetVideoMode(800, 480, 32, SDL_OPENGL) as it is now, and this in platform/sdl/video.c is the culprit, right ?

sdl.screen = SDL_SetVideoMode(
                sdl.canvasw, sdl.canvash, sizeof(av_pixel), sdl.sdlarg);

Cheers, Sam

**Comment by sviscapi** [comment]
And yes pandorawiki.org should be accurate, it's our "official" wiki :)

Cheers, Sam

**Comment by letoram** [comment]
that should be the fix, though I wonder what version of the context you'll actually get from that (SDL_OPENGLES doesn't exist in official SDL1.2) - a GLES < 2.0 won't be able to render much - then we'll see how well FBO support works (if at all), and how slow it gets (havn't done any real optimizations for ARM devices at this stage, so there's no NEON version of some of the math-ops and it's not conservative at all in regards to memory bandwidth consumption).

**Comment by sviscapi** [comment]
Hi,

I tried to hack my way through platform/sdl/video.c, but with little success so far (I'm obviously not a dev ;) ).

I tried to hardcode sdl.screen = SDL_SetVideoMode(
800, 480, 16, SDL_OPENGLES); but that didn't work.

I also tried to change the struct at the beginning of the file:

int sdlarg = SDL_OPENGLES;
size_t canvasw = 800, canvash = 480;

But that didn't work either...

Could you please give me a hand ? 

Cheers, Sam

**Comment by letoram** [comment]
did it fail with the same message or did you get anything more?
Can try verifying with GDB, since you have a debug build:

gdb --args ./arcan /path/to/appl
b video.c:397
run
singlestep with n, if it takes the path at 408/409 we know it's the SDL screen part that breaks.
If so, try commenting out all the calls to SDL_GL_SetAttributes to see if there's something with our requirements on the GL setup (373 to 377)

**Comment by sviscapi** [comment]
Hi,

Sorry for the late reply.

I meant it failed to compile, because I don't think my C syntax is correct ;) That's where your help could come in handy. 

I also tried to run gdb but it failed:

/media/Pandora1/dev/arcan/arcan/build$ gdb --args ./arcan ../data/appl
GNU gdb (GDB) 7.6.50.20131021-cvs
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "armv7l-unknown-linux-gnueabi".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./arcan...done.
(gdb) b video.c:397
Breakpoint 1 at 0x8a80c: file /media/Pandora1/dev/arcan/arcan/src/platform/sdl/video.c, line 397.
(gdb) run
Starting program: /media/Pandora1/dev/arcan/arcan/build/arcan ../data/appl
warning: Unable to find libthread_db matching inferior's thread library, thread debugging will not be available.
warning: Unable to find libthread_db matching inferior's thread library, thread debugging will not be available.
Couldn't load application (../data/appl)
	tried to load relative to current directory
[Inferior 1 (process 4578) exited with code 01]
(gdb) quit

What am I doing wrong ?

Cheers, Sam

**Comment by sviscapi** [comment]
Recompiled with all calls to SDL_GL_SetAttributes commented out, but arcan still fails the same way:

/media/Pandora1/dev/arcan/arcan/build$ ./arcan -p ../data/resources/ ../data/appl/welcome
Notice: [SDL] Video Info: 800, 480, hardware acceleration: no, window manager: yes, MSAA: 4
platform_video_init() failed.
Error: couldn't initialize video subsystem. Check permissions,  try other video platform options (-f, -w, -h)
Video platform environment variables:
	ARCAN_VIDEO_MULTISAMPLES=1 - attempt to enable multisampling

Video platform initialization failed
Aborted

Cheers, Sam

**Comment by letoram** [comment]
ah I understand what you mean. The problem with gdb looks like the userspace environment on your pandora + arcan dependencies dosn't play well together - without some luck, fixing that may cost more than what it's worth.

What was the compiler output when you tried the 
"sdl.screen = SDL_SetVideoMode(800, 480, 16, SDL_OPENGLES); but that didn't work."

**Comment by sviscapi** [comment]
Here you go :)

[ 45%] Building C object CMakeFiles/arcan.dir/platform/sdl/video.c.o
/media/Pandora1/dev/arcan/arcan/src/platform/sdl/video.c: In function ���platform_video_restore_external���:
/media/Pandora1/dev/arcan/arcan/src/platform/sdl/video.c:78:17: error: ���SDL_OPENGLES��� undeclared (first use in this function)
   800, 480, 16, SDL_OPENGLES);
                 ^~~~~~~~~~~~
/media/Pandora1/dev/arcan/arcan/src/platform/sdl/video.c:78:17: note: each undeclared identifier is reported only once for each function it appears in
CMakeFiles/arcan.dir/build.make:998: recipe for target 'CMakeFiles/arcan.dir/platform/sdl/video.c.o' failed
make[2]: *** [CMakeFiles/arcan.dir/platform/sdl/video.c.o] Error 1
CMakeFiles/Makefile2:68: recipe for target 'CMakeFiles/arcan.dir/all' failed
make[1]: *** [CMakeFiles/arcan.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

I think I need to declare SDL_OPENGLES prior to using it, but I'm not sure how to do this ? Would "char SDL_OPENGLES" in the static struct part work ?

Cheers, Sam

**Comment by sviscapi** [comment]
It just occurred to me that I could be using the wrong SDL library...

https://pandorawiki.org/GLES#1:_Grab_the_modified_version_of_SDL

I'll keep you posted ASAP.

Cheers, Sam

**Comment by letoram** [comment]
I'm on IRC for most of the day if you want quicker replies

**Comment by letoram** [comment]
Closing issue as the build parts have been solved (driver issues are a separate matter)
